### ISSUE TITLE
static build does not work

### ISSUE THREAD

**Issue by gour** [NorfairKing/smos#294] opened 2024-11-21 10:23 UTC
Hello,

Taskwarrior user here who would like to try `smos`...I'm on Siduction (Linux 6.11.9-1-siduction-amd64 #1 SMP PREEMPT_DYNAMIC siduction 6.11-9 (2024-11-17) x86_64 GNU/Linux) and when I try to run it I get:

```
~/.local/bin 
❯ smos
exec: Failed to execute process '/home/userid/.local/bin/smos': The file exists and is executable. Check the interpreter or linker?

~/.local/bin 
❯ strace smos
execve("/home/userid/.local/bin/smos", ["smos"], 0x7fff32457f30 /* 59 vars */) = -1 ENOENT (No such file or directory)
strace: exec: No such file or directory
+++ exited with 1 +++
****
```

Any idea?

The whole system, along with InTray and Tickler looks interesting for user familiar to work within Terminal, but, unfortunately, we're not all on NixOS. :disappointed:

**Comment by NorfairKing** [comment] 2024-11-21 10:28
@gour I can't seem to figure out what the issue is based on this error message.
It looks like your architecture is right so I think that's not the issue.
You don't need to be on NixOS to use nix.
You can try `nix run github:NorfairKing/smos` to try smos out.
We can then work together to get the static build working for you too.

**Comment by gour** [comment] 2024-11-21 10:34
Hello,

thank you for prompt reply!

> You can try `nix run github:NorfairKing/smos` to try smos out. We can then work together to get the static build working for you too.

I've installed nix and it is available:

```
$ whereis nix
nix: /usr/bin/nix /usr/lib/nix /etc/nix /usr/libexec/nix /usr/share/man/man1/nix.1.gz
```

but running it gives:

```
$ nix run github:NorfairKing/smos
error: experimental Nix feature 'nix-command' is disabled; add '--extra-experimental-features nix-command' to enable it
```

What's next to try?

**Comment by NorfairKing** [comment] 2024-11-21 11:03
> What's next to try?

Try what it says here in the error:
```
add '--extra-experimental-features nix-command' to enable it
```

Then you'll get an error about `flakes` not being enabled, so the full command will (probably) be

```
nix run github:NorfairKing/smos --extra-experimental-features nix-command --extra-experimental-features flakes
```

**Comment by gour** [comment] 2024-11-21 11:10
> nix run github:NorfairKing/smos --extra-experimental-features nix-command --extra-experimental-features flakes

```
$  nix run github:NorfairKing/smos --extra-experimental-features nix-command --extra-experimental-features flakes
error: getting status of '/nix/var/nix/daemon-socket/socket': Permission denied
```

**Comment by NorfairKing** [comment] 2024-11-21 12:35
Huh that sounds like you have a single-user install of nix instead of a multi-user install.
But I'm surprised that that would be a problem.

Can you `ldd` the original static binary please?
`ENOENT` usually means a missing library but that shouldn't happen for the static binaries.

**Comment by gour** [comment] 2024-11-21 12:39
> Huh that sounds like you have a single-user install of nix instead of a multi-user install. But I'm surprised that that would be a problem.

Nope, I installed it via system package manager (apt).


> Can you `ldd` the original static binary please? `ENOENT` usually means a missing library but that shouldn't happen for the static binaries.

Tried that already, but nothing suspicious, afaict:

```
 $ ldd ~/bin/smos
	linux-vdso.so.1 (0x00007f6730d00000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6730bfe000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f6730bde000)
	libncursesw.so.6 => /lib/x86_64-linux-gnu/libncursesw.so.6 (0x00007f6730ba4000)
	libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f6730b1a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6730922000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f673091d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6730918000)
	libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007f673090b000)
	libelf.so.1 => /lib/x86_64-linux-gnu/libelf.so.1 (0x00007f67308ed000)
	libdw.so.1 => /lib/x86_64-linux-gnu/libdw.so.1 (0x00007f6730833000)
	/nix/store/kpy2cyd05vdr6j1h200av81fnlxl1jw0-glibc-2.39-52/lib/ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2 (0x00007f6730d02000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f67307fc000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f6730734000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f6730703000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f67306f0000)
```

**Comment by NorfairKing** [comment] 2024-11-21 12:41
> Tried that already, but nothing suspicious, afaict:

This is very suspicious, in fact.
Those are the wrong binaries :P
They should have no dynamically linked libraries.

There's the issue. The website is somehow hosting non-static builds. I'll need to fix that.
Thank you very much for pointing that out!

In the meantime you can try a multi-user install of nix and try the above, or use the web editor at https://smos.online.

**Comment by gour** [comment] 2024-11-21 12:59
> This is very suspicious, in fact. Those are the wrong binaries :P They should have no dynamically linked libraries.
> 

It must be I was blind (not seeing reference to the nix store) and stupid as well, forgetting there should be no references to systems libs. :-1: 

> There's the issue. The website is somehow hosting non-static builds. I'll need to fix that. Thank you very much for pointing that out!

You're welcome!

> In the meantime you can try a multi-user install of nix and try the above, or use the web editor at https://smos.online.

I was able to get `smos` built by running the above cmd as root. :sunglasses: 

However, eager to test witth the normal static build...

**Comment by NorfairKing** [comment] 2024-11-22 15:12
Will be fixed once this is released.
https://github.com/NorfairKing/smos/commit/a1d9294802ec52d7f6f2857aabcd3cef821bc150

Please give me some time, I have one month old baby keeping me up at night right now :)

**Comment by gour** [comment] 2024-11-22 17:08
> Will be fixed once this is released. [a1d9294](https://github.com/NorfairKing/smos/commit/a1d9294802ec52d7f6f2857aabcd3cef821bc150)

Good.

> Please give me some time, I have one month old baby keeping me up at night right now :)

I know what you're talking about...our "baby" is over 10 now. :smile:

**Closed as completed** 2024-11-29 18:13 UTC
